-- Align first-party diagnostics with the approved privacy/rate-limit design.
create table if not exists public.crash_ingest_limits (
  id bigint generated by default as identity primary key,
  client_key text not null check (client_key ~ '^[0-9a-f]{64}$'),
  accepted_at timestamptz not null default now()
);

create index if not exists crash_ingest_limits_client_time_idx
  on public.crash_ingest_limits(client_key, accepted_at desc);
create index if not exists crash_ingest_limits_expiry_idx
  on public.crash_ingest_limits(accepted_at);

alter table public.crash_ingest_limits enable row level security;
revoke all on public.crash_ingest_limits from public, anon, authenticated;

alter table public.crash_events drop constraint if exists crash_events_message_check;
alter table public.crash_events add constraint crash_events_message_check
  check (char_length(message) <= 2048);
alter table public.crash_events drop constraint if exists crash_events_stack_trace_check;
alter table public.crash_events add constraint crash_events_stack_trace_check
  check (char_length(stack_trace) between 1 and 32768);

create or replace function public.record_crash_report_v2(
  p_client_key text,
  p_fingerprint text,
  p_package_id text,
  p_version_code bigint,
  p_version_name text,
  p_android_sdk integer,
  p_device_manufacturer text,
  p_device_model text,
  p_exception_class text,
  p_message text,
  p_stack_trace text,
  p_occurred_at timestamptz
) returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_count integer;
  v_event_id uuid;
begin
  if p_client_key !~ '^[0-9a-f]{64}$' then raise exception 'Invalid client key'; end if;
  if p_fingerprint !~ '^[0-9a-f]{64}$' then raise exception 'Invalid fingerprint'; end if;
  if p_package_id <> 'com.apkstore.client' then raise exception 'Invalid package'; end if;
  if p_version_code <= 0 or char_length(p_version_name) not between 1 and 64 then raise exception 'Invalid version'; end if;
  if p_android_sdk not between 26 and 100 then raise exception 'Invalid Android version'; end if;
  if char_length(p_device_manufacturer) > 80 or char_length(p_device_model) > 120 then raise exception 'Invalid device metadata'; end if;
  if char_length(p_exception_class) not between 1 and 180 or char_length(p_message) > 2048 or char_length(p_stack_trace) not between 1 and 32768 then
    raise exception 'Invalid exception metadata';
  end if;
  if p_occurred_at > now() + interval '5 minutes' or p_occurred_at < now() - interval '90 days' then raise exception 'Invalid crash timestamp'; end if;

  -- Serialize checks per derived client key so concurrent requests cannot bypass the rolling-hour cap.
  perform pg_advisory_xact_lock(hashtextextended(p_client_key, 0));
  delete from public.crash_ingest_limits where accepted_at < now() - interval '24 hours';
  select count(*) into v_count
  from public.crash_ingest_limits
  where client_key = p_client_key and accepted_at > now() - interval '1 hour';
  if v_count >= 20 then raise exception 'Crash report rate limit exceeded'; end if;
  insert into public.crash_ingest_limits(client_key) values (p_client_key);

  insert into public.crash_issues(
    fingerprint,package_id,title,exception_class,status,first_seen_at,last_seen_at,
    event_count,latest_version_code,latest_version_name,updated_at
  ) values (
    p_fingerprint,p_package_id,p_exception_class,p_exception_class,'open',p_occurred_at,p_occurred_at,
    1,p_version_code,p_version_name,now()
  )
  on conflict (fingerprint) do update set
    first_seen_at = least(public.crash_issues.first_seen_at, excluded.first_seen_at),
    last_seen_at = greatest(public.crash_issues.last_seen_at, excluded.last_seen_at),
    event_count = public.crash_issues.event_count + 1,
    latest_version_name = case when excluded.latest_version_code >= public.crash_issues.latest_version_code then excluded.latest_version_name else public.crash_issues.latest_version_name end,
    latest_version_code = greatest(public.crash_issues.latest_version_code, excluded.latest_version_code),
    updated_at = now();

  insert into public.crash_events(
    fingerprint,package_id,version_code,version_name,android_sdk,device_manufacturer,
    device_model,exception_class,message,stack_trace,occurred_at
  ) values (
    p_fingerprint,p_package_id,p_version_code,p_version_name,p_android_sdk,p_device_manufacturer,
    p_device_model,p_exception_class,p_message,p_stack_trace,p_occurred_at
  ) returning id into v_event_id;

  return v_event_id;
end $$;

revoke all on function public.record_crash_report_v2(text,text,text,bigint,text,integer,text,text,text,text,text,timestamptz) from public, anon, authenticated;
grant execute on function public.record_crash_report_v2(text,text,text,bigint,text,integer,text,text,text,text,text,timestamptz) to service_role;
