-- APK STORE crash reporting schema. Public clients never write these tables directly;
-- the crash-report Edge Function calls the SECURITY DEFINER RPC with service-role auth.

create table if not exists public.crash_reports (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null check (fingerprint ~ '^[0-9a-f]{64}$'),
  package_id text not null check (package_id = 'com.apkstore.client'),
  version_code bigint not null check (version_code > 0),
  version_name text not null check (length(version_name) between 1 and 64),
  android_sdk integer,
  device_manufacturer text,
  device_model text,
  exception_class text not null check (length(exception_class) between 1 and 180),
  message text not null default '',
  stack_trace text not null check (length(stack_trace) > 0),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  report_type text not null default 'crash' check (report_type in ('crash','handled'))
);

create table if not exists public.crash_issues (
  fingerprint text primary key check (fingerprint ~ '^[0-9a-f]{64}$'),
  package_id text not null check (package_id = 'com.apkstore.client'),
  title text not null check (char_length(title) between 1 and 180),
  exception_class text not null check (char_length(exception_class) between 1 and 180),
  status text not null default 'open' check (status in ('open','resolved','ignored')),
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  event_count bigint not null default 1 check (event_count > 0),
  latest_version_code bigint not null check (latest_version_code > 0),
  latest_version_name text not null check (char_length(latest_version_name) between 1 and 64),
  updated_at timestamptz not null default now()
);

create table if not exists public.crash_events (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null references public.crash_issues(fingerprint) on delete restrict,
  package_id text not null check (package_id = 'com.apkstore.client'),
  version_code bigint not null check (version_code > 0),
  version_name text not null check (char_length(version_name) between 1 and 64),
  android_sdk integer not null check (android_sdk between 26 and 100),
  device_manufacturer text not null check (char_length(device_manufacturer) <= 80),
  device_model text not null check (char_length(device_model) <= 120),
  exception_class text not null check (char_length(exception_class) between 1 and 180),
  message text not null default '' check (char_length(message) <= 2048),
  stack_trace text not null check (char_length(stack_trace) between 1 and 32768),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now()
);

create table if not exists public.crash_ingest_limits (
  id bigint generated by default as identity primary key,
  client_key text not null check (client_key ~ '^[0-9a-f]{64}$'),
  accepted_at timestamptz not null default now()
);

create table if not exists public.crash_rate_limits (
  rate_key text not null check (rate_key ~ '^[0-9a-f]{64}$'),
  window_started_at timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  primary key (rate_key, window_started_at)
);

create index if not exists crash_reports_fingerprint_received_idx on public.crash_reports(fingerprint, received_at desc);
create index if not exists crash_reports_received_idx on public.crash_reports(received_at desc);
create index if not exists crash_reports_version_received_idx on public.crash_reports(version_code, received_at desc);
create index if not exists crash_issues_status_last_seen_idx on public.crash_issues(status, last_seen_at desc);
create index if not exists crash_events_fingerprint_received_idx on public.crash_events(fingerprint, received_at desc);
create index if not exists crash_events_version_received_idx on public.crash_events(version_code, received_at desc);
create index if not exists crash_ingest_limits_client_time_idx on public.crash_ingest_limits(client_key, accepted_at desc);
create index if not exists crash_ingest_limits_expiry_idx on public.crash_ingest_limits(accepted_at);
create index if not exists crash_rate_limits_window_idx on public.crash_rate_limits(window_started_at);

alter table public.crash_reports enable row level security;
alter table public.crash_issues enable row level security;
alter table public.crash_events enable row level security;
alter table public.crash_ingest_limits enable row level security;
alter table public.crash_rate_limits enable row level security;

revoke all on public.crash_reports from anon, authenticated;
revoke all on public.crash_issues from anon, authenticated;
revoke all on public.crash_events from anon, authenticated;
revoke all on public.crash_ingest_limits from anon, authenticated;
revoke all on public.crash_rate_limits from anon, authenticated;

create or replace function public.record_crash_report_v2(
  p_client_key text,
  p_fingerprint text,
  p_package_id text,
  p_version_code bigint,
  p_version_name text,
  p_android_sdk integer,
  p_device_manufacturer text,
  p_device_model text,
  p_exception_class text,
  p_message text,
  p_stack_trace text,
  p_occurred_at timestamptz
) returns uuid
language plpgsql
security definer
set search_path = 'public', 'pg_temp'
as $$
declare
  v_count integer;
  v_event_id uuid;
begin
  if p_client_key !~ '^[0-9a-f]{64}$' then raise exception 'Invalid client key'; end if;
  if p_fingerprint !~ '^[0-9a-f]{64}$' then raise exception 'Invalid fingerprint'; end if;
  if p_package_id <> 'com.apkstore.client' then raise exception 'Invalid package'; end if;
  if p_version_code <= 0 or char_length(p_version_name) not between 1 and 64 then raise exception 'Invalid version'; end if;
  if p_android_sdk not between 26 and 100 then raise exception 'Invalid Android version'; end if;
  if char_length(p_device_manufacturer) > 80 or char_length(p_device_model) > 120 then raise exception 'Invalid device metadata'; end if;
  if char_length(p_exception_class) not between 1 and 180 or char_length(p_message) > 2048 or char_length(p_stack_trace) not between 1 and 32768 then raise exception 'Invalid exception metadata'; end if;
  if p_occurred_at > now() + interval '5 minutes' or p_occurred_at < now() - interval '90 days' then raise exception 'Invalid crash timestamp'; end if;

  perform pg_advisory_xact_lock(hashtextextended(p_client_key, 0));
  delete from public.crash_ingest_limits where accepted_at < now() - interval '24 hours';
  select count(*) into v_count
    from public.crash_ingest_limits
   where client_key = p_client_key and accepted_at > now() - interval '1 hour';
  if v_count >= 20 then raise exception 'Crash report rate limit exceeded'; end if;
  insert into public.crash_ingest_limits(client_key) values (p_client_key);

  insert into public.crash_issues(
    fingerprint, package_id, title, exception_class, status,
    first_seen_at, last_seen_at, event_count,
    latest_version_code, latest_version_name, updated_at)
  values (
    p_fingerprint, p_package_id, p_exception_class, p_exception_class, 'open',
    p_occurred_at, p_occurred_at, 1,
    p_version_code, p_version_name, now())
  on conflict (fingerprint) do update set
    first_seen_at = least(public.crash_issues.first_seen_at, excluded.first_seen_at),
    last_seen_at = greatest(public.crash_issues.last_seen_at, excluded.last_seen_at),
    event_count = public.crash_issues.event_count + 1,
    latest_version_name = case
      when excluded.latest_version_code >= public.crash_issues.latest_version_code
      then excluded.latest_version_name else public.crash_issues.latest_version_name end,
    latest_version_code = greatest(public.crash_issues.latest_version_code, excluded.latest_version_code),
    updated_at = now();

  insert into public.crash_events(
    fingerprint, package_id, version_code, version_name, android_sdk,
    device_manufacturer, device_model, exception_class, message, stack_trace, occurred_at)
  values (
    p_fingerprint, p_package_id, p_version_code, p_version_name, p_android_sdk,
    p_device_manufacturer, p_device_model, p_exception_class, p_message, p_stack_trace, p_occurred_at)
  returning id into v_event_id;

  return v_event_id;
end
$$;

revoke all on function public.record_crash_report_v2(text,text,text,bigint,text,integer,text,text,text,text,text,timestamptz) from public, anon, authenticated;
grant execute on function public.record_crash_report_v2(text,text,text,bigint,text,integer,text,text,text,text,text,timestamptz) to service_role;
